# **District data cleaning**

This script is to clean and merge the 5 district files. We check the null values, correct the typos and impute missing values if necessary.

---

### **Summary**
1. **Explore Data and Classify Columns** [(→)](#1.-Explore-Data-and-Classify-Columns)\
Have a look at the data, drop some unnecessary data, and classify the columns (e.g. college or high school related). 
2. **Get Student's Basic Info** [(→)](#2.-Get-Student's-Basic-Info)\
Create dataframes named "student_info" for each district to store the desired info for output purpose. Find the 9th grade year of the students, and their basic info and indicators (e.g. high_school_grad, college_grad).
3. **Get Student's High School Info** [(→)](#3.-Get-Student's-High-School-Info)\
Get student's high school related info (high school code).
4. **Get Student's College Info** [(→)](#4.-Get-Student's-College-Info)\
Get student's college related info (e.g. degree, college type).
5. **Drop Students and Save to Files** [(→)](#5.-Drop-Students-and-Save-to-Files)\
Drop the students who doesn't have any college info (like some students was 9th grade in 2006 while the collected college data starts from 2011). Then save the dataframes separately by districts and also to a combined file.

---

In [1]:
# Irene

import pandas as pd
import numpy as np
import re
from collections import Counter
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

---

#### **1. Explore Data and Classify Columns** 
[(→)](#Summary)

In [2]:
# Irene

df1 = pd.read_feather('df1.feather')
df2 = pd.read_feather('df2.feather')
df3 = pd.read_feather('df3.feather')
df4 = pd.read_feather('df4.feather')
df5 = pd.read_feather('df5.feather')
print(df1.shape, df2.shape, df3.shape, df4.shape, df5.shape)

# a list storing each df and their names in string format
df_l = [('df1', df1), ('df2', df2), ('df3', df3), ('df4', df4), ('df5', df5)]
# a dict storing different information about each df
df_d = {'df1':{}, 'df2':{}, 'df3':{}, 'df4':{}, 'df5':{}}

(71475, 804) (33071, 701) (38641, 838) (34785, 783) (77040, 713)

In [3]:
# Irene

# drop duplicate study_id
def dropDuplicate(df):
    df.drop_duplicates(subset=['study_id'], keep=False, inplace=True)
    df.drop(columns='duplicate', inplace=True)
    display(df.head(0))
    
for df_name, df in df_l:
    dropDuplicate(df)
print(df1.shape, df2.shape, df3.shape, df4.shape, df5.shape)

Empty DataFrame
Columns: [study_id, district, birth_date, gender, hispanic_indicator, ethnicity, ethnicity_extra2, ethnicity_extra3, ethnicity_extra4, ethnicity_extra5, ethnicity_recoded, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2013grade_level, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2018grade_level, FY2014high_school_code1, FY2015high_school_code1, FY2016high_school_code1, FY2017high_school_code1, FY2019high_school_code1, FY2013gpa_school1, FY2014gpa_school1, FY2015gpa_school1, FY2016gpa_school1, FY2017gpa_school1, FY2018gpa_school1, FY2013days_absent_school1, FY2014days_absent_school1, FY2015days_absent_school1, FY2016days_absent_school1, FY2017days_absent_school1, FY2018days_absent_school1, FY2013unweightedclassrank_school1, FY2014unweightedclassrank_school1, FY2015unweightedclassrank_school1, FY2016unweightedclassrank_school1, FY2017unweightedclassrank_school1, FY2018unweightedclassrank_school1, FY2013collegecoregpa, FY2014collegecoregpa, FY2015collegecoregpa, FY2016collegecoregpa, FY2017collegecoregpa, FY2018collegecoregpa, FY2013collegecoreclassrank, FY2014collegecoreclassrank, FY2015collegecoreclassrank, FY2016collegecoreclassrank, FY2017collegecoreclassrank, FY2018collegecoreclassrank, FY2010ACT_composite_score, FY2010ACT_composite_perf_level, FY2010ACT_english_score, FY2010ACT_english_perf_level, FY2010ACT_reading_score, FY2010ACT_reading_perf_level, FY2010ACT_math_score, FY2010ACT_math_perf_level, FY2010ACT_science_score, FY2010ACT_science_perf_level, FY2012ACT_composite_score, FY2012ACT_composite_perf_level, FY2012ACT_english_score, FY2012ACT_english_perf_level, FY2012ACT_reading_score, FY2012ACT_reading_perf_level, FY2012ACT_math_score, FY2012ACT_math_perf_level, FY2012ACT_science_score, FY2012ACT_science_perf_level, FY2013ACT_composite_score, FY2013ACT_composite_perf_level, FY2013ACT_english_score, FY2013ACT_english_perf_level, FY2013ACT_reading_score, FY2013ACT_reading_perf_level, FY2013ACT_math_score, FY2013ACT_math_perf_level, FY2013ACT_science_score, FY2013ACT_science_perf_level, FY2014ACT_composite_score, FY2014ACT_composite_perf_level, FY2014ACT_english_score, FY2014ACT_english_perf_level, FY2014ACT_reading_score, FY2014ACT_reading_perf_level, FY2014ACT_math_score, FY2014ACT_math_perf_level, FY2014ACT_science_score, FY2014ACT_science_perf_level, FY2015ACT_composite_score, FY2015ACT_composite_perf_level, FY2015ACT_english_score, FY2015ACT_english_perf_level, FY2015ACT_reading_score, ...]
Index: []

Empty DataFrame
Columns: [study_id, district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2018grade_level, FY2014gpa_school1, FY2015gpa_school1, FY2016gpa_school1, FY2017gpa_school1, FY2018gpa_school1, FY2014AIMS_reading_score, FY2014AIMS_reading_perf_level, FY2014AIMS_writing_score, FY2014AIMS_writing_perf_level, FY2014AIMS_math_score, FY2014AIMS_math_perf_level, FY2015AIMS_reading_score, FY2015AIMS_reading_perf_level, FY2015AIMS_writing_score, FY2015AIMS_writing_perf_level, FY2015AIMS_math_score, FY2015AIMS_math_perf_level, FY2015AzMerit_ELA9_score, FY2015AzMerit_ELA9_perf_level, FY2015AzMerit_ELA10_score, FY2015AzMerit_ELA10_perf_level, FY2015AzMerit_ELA11_score, FY2015AzMerit_ELA11_perf_level, FY2015AzMerit_unspecified_math_score, FY2015AzMerit_unspecified_math_perf_level, FY2016AzMerit_ELA9_score, FY2016AzMerit_ELA9_perf_level, FY2016AzMerit_ELA10_score, FY2016AzMerit_ELA10_perf_level, FY2016AzMerit_ELA11_score, FY2016AzMerit_ELA11_perf_level, FY2016AzMerit_unspecified_math_score, FY2016AzMerit_unspecified_math_perf_level, FY2017AzMerit_ELA9_score, FY2017AzMerit_ELA9_perf_level, FY2017AzMerit_ELA10_score, FY2017AzMerit_ELA10_perf_level, FY2017AzMerit_ELA11_score, FY2017AzMerit_ELA11_perf_level, FY2017AzMerit_unspecified_math_score, FY2017AzMerit_unspecified_math_perf_level, FY2018AzMerit_ELA9_score, FY2018AzMerit_ELA9_perf_level, FY2018AzMerit_ELA10_score, FY2018AzMerit_ELA10_perf_level, FY2018AzMerit_ELA11_score, FY2018AzMerit_ELA11_perf_level, FY2018AzMerit_unspecified_math_score, FY2018AzMerit_unspecified_math_perf_level, FY2014AP_englishLang_score, FY2014AP_englishLang_course_letter_grade, FY2014AP_englishLang_course_number_grade, FY2014AP_englishLit_score, FY2014AP_englishLit_course_letter_grade, FY2014AP_englishLit_course_number_grade, FY2014AP_biology_score, FY2014AP_biology_course_letter_grade, FY2014AP_biology_course_number_grade, FY2014AP_chemistry_score, FY2014AP_chemistry_course_letter_grade, FY2014AP_chemistry_course_number_grade, FY2014AP_physicsB_score, FY2014AP_physicsB_course_letter_grade, FY2014AP_physicsB_course_number_grade, FY2014AP_physicsCEM_score, FY2014AP_physicsCEM_course_letter_grade, FY2014AP_physicsCEM_course_number_grade, FY2014AP_physicsCMech_score, FY2014AP_physicsCMech_course_letter_grade, FY2014AP_physicsCMech_course_number_grade, FY2014AP_environmentSci_score, FY2014AP_environmentSci_course_letter_grade, FY2014AP_environmentSci_course_number_grade, FY2014AP_calculusAB_score, FY2014AP_calculusAB_course_letter_grade, FY2014AP_calculusAB_course_number_grade, FY2014AP_calculusBC_score, FY2014AP_calculusBC_course_letter_grade, FY2014AP_calculusBC_course_number_grade, FY2014AP_calculusBCABsubscore_score, FY2014AP_calculusBCABsubscore_course_letter_grade, FY2014AP_calculusBCABsubscore_course_number_grade, FY2014AP_statistics_score, FY2014AP_statistics_course_letter_grade, FY2014AP_statistics_course_number_grade, FY2014AP_govtComparative_score, FY2014AP_govtComparative_course_letter_grade, ...]
Index: []

Empty DataFrame
Columns: [study_id, district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2018grade_level, FY2014high_school_code1, FY2014high_school_code2, FY2014high_school_code3, FY2015high_school_code1, FY2015high_school_code2, FY2016high_school_code1, FY2016high_school_code2, FY2017high_school_code1, FY2018high_school_code1, FY2014gpa_school1, FY2014gpa_school2, FY2014gpa_school3, FY2015gpa_school1, FY2015gpa_school2, FY2016gpa_school1, FY2016gpa_school2, FY2017gpa_school1, FY2018gpa_school1, FY2014unweightedclassrank_school1, FY2014unweightedclassrank_school2, FY2014unweightedclassrank_school3, FY2015unweightedclassrank_school1, FY2015unweightedclassrank_school2, FY2016unweightedclassrank_school1, FY2016unweightedclassrank_school2, FY2017unweightedclassrank_school1, FY2018unweightedclassrank_school1, FY2017ACT_composite_score, FY2017ACT_english_score, FY2017ACT_reading_score, FY2017ACT_math_score, FY2017ACT_science_score, FY2018ACT_composite_score, FY2018ACT_english_score, FY2018ACT_reading_score, FY2018ACT_math_score, FY2018ACT_science_score, FY2019ACT_composite_score, FY2019ACT_english_score, FY2019ACT_reading_score, FY2019ACT_math_score, FY2019ACT_science_score, FY2017PSAT_Total_score, FY2017PSAT_English_score, FY2017PSAT_Reading_score, FY2017PSAT_Writing_score, FY2017PSAT_Math_score, FY2018PSAT_Total_score, FY2018PSAT_English_score, FY2018PSAT_Reading_score, FY2018PSAT_Writing_score, FY2018PSAT_Math_score, FY2016SAT_Total_score, FY2016SAT_English_score, FY2016SAT_Math_score, FY2017SAT_Total_score, FY2017SAT_English_score, FY2017SAT_Math_score, FY2018SAT_Total_score, FY2018SAT_English_score, FY2018SAT_Math_score, FY2019SAT_Total_score, FY2019SAT_English_score, FY2019SAT_Math_score, FY2009AIMS_reading_score, FY2009AIMS_reading_perf_level, FY2009AIMS_writing_score, FY2009AIMS_writing_perf_level, FY2009AIMS_math_score, FY2009AIMS_math_perf_level, FY2009AIMS_science_score, FY2009AIMS_science_perf_level, FY2010AIMS_reading_score, FY2010AIMS_reading_perf_level, FY2010AIMS_writing_score, FY2010AIMS_writing_perf_level, FY2010AIMS_math_score, FY2010AIMS_math_perf_level, FY2010AIMS_science_score, FY2010AIMS_science_perf_level, FY2011AIMS_reading_score, FY2011AIMS_reading_perf_level, FY2011AIMS_writing_score, FY2011AIMS_writing_perf_level, FY2011AIMS_math_score, FY2011AIMS_math_perf_level, FY2011AIMS_science_score, ...]
Index: []

Empty DataFrame
Columns: [study_id, district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2014high_school_code1, FY2014high_school_code2, FY2014high_school_code3, FY2015high_school_code1, FY2015high_school_code2, FY2015high_school_code3, FY2016high_school_code1, FY2016high_school_code2, FY2016high_school_code3, FY2017high_school_code1, FY2017high_school_code2, FY2017high_school_code3, FY2014days_absent_school1, FY2014days_absent_school2, FY2014days_absent_school3, FY2015days_absent_school1, FY2015days_absent_school2, FY2015days_absent_school3, FY2016days_absent_school1, FY2016days_absent_school2, FY2016days_absent_school3, FY2017days_absent_school1, FY2017days_absent_school2, FY2017days_absent_school3, FY2013ACT_composite_score, FY2013ACT_english_score, FY2013ACT_reading_score, FY2013ACT_math_score, FY2013ACT_science_score, FY2015ACT_composite_score, FY2015ACT_english_score, FY2015ACT_reading_score, FY2015ACT_math_score, FY2015ACT_science_score, FY2016ACT_composite_score, FY2016ACT_english_score, FY2016ACT_reading_score, FY2016ACT_math_score, FY2016ACT_science_score, FY2017ACT_composite_score, FY2017ACT_english_score, FY2017ACT_reading_score, FY2017ACT_math_score, FY2017ACT_science_score, FY2012AIMS_science_score, FY2012AIMS_science_perf_level, FY2013AIMS_science_score, FY2013AIMS_science_perf_level, FY2014AIMS_science_score, FY2014AIMS_science_perf_level, FY2016AIMS_science_score, FY2016AIMS_science_perf_level, FY2015AzMerit_ELA9_score, FY2015AzMerit_ELA9_perf_level, FY2015AzMerit_ELA10_score, FY2015AzMerit_ELA10_perf_level, FY2015AzMerit_ELA11_score, FY2015AzMerit_ELA11_perf_level, FY2015AzMerit_AlgI_score, FY2015AzMerit_AlgI_perf_level, FY2015AzMerit_Geometry_score, FY2015AzMerit_Geometry_perf_level, FY2015AzMerit_AlgII_score, FY2015AzMerit_AlgII_perf_level, FY2016AzMerit_ELA9_score, FY2016AzMerit_ELA9_perf_level, FY2016AzMerit_ELA10_score, FY2016AzMerit_ELA10_perf_level, FY2016AzMerit_ELA11_score, FY2016AzMerit_ELA11_perf_level, FY2017AzMerit_ELA9_score, FY2017AzMerit_ELA9_perf_level, FY2017AzMerit_ELA10_score, FY2017AzMerit_ELA10_perf_level, FY2017AzMerit_ELA11_score, FY2017AzMerit_ELA11_perf_level, FY2017AzMerit_AlgI_score, FY2017AzMerit_AlgI_perf_level, FY2017AzMerit_Geometry_score, FY2017AzMerit_Geometry_perf_level, FY2017AzMerit_AlgII_score, FY2017AzMerit_AlgII_perf_level, FY2018AzMerit_ELA9_score, FY2018AzMerit_ELA9_perf_level, FY2018AzMerit_ELA10_score, FY2018AzMerit_ELA10_perf_level, FY2018AzMerit_ELA11_score, FY2018AzMerit_ELA11_perf_level, ...]
Index: []

Empty DataFrame
Columns: [study_id, district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2013grade_level, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2013high_school_code1, FY2013high_school_code2, FY2013high_school_code3, FY2014high_school_code1, FY2014high_school_code2, FY2014high_school_code3, FY2015high_school_code1, FY2015high_school_code2, FY2015high_school_code3, FY2015high_school_code4, FY2016high_school_code1, FY2016high_school_code2, FY2016high_school_code3, FY2017high_school_code1, FY2017high_school_code2, FY2017high_school_code3, FY2017high_school_code4, FY2013gpa_school1, FY2014gpa_school1, FY2015gpa_school1, FY2016gpa_school1, FY2017gpa_school1, FY2013days_absent_school1, FY2013days_absent_school2, FY2013days_absent_school3, FY2014days_absent_school1, FY2014days_absent_school2, FY2014days_absent_school3, FY2015days_absent_school1, FY2015days_absent_school2, FY2015days_absent_school3, FY2015days_absent_school4, FY2016days_absent_school1, FY2016days_absent_school2, FY2016days_absent_school3, FY2017days_absent_school1, FY2017days_absent_school2, FY2017days_absent_school3, FY2017days_absent_school4, FY2013year_end_exit_code, FY2014year_end_exit_code, FY2015year_end_exit_code, FY2016year_end_exit_code, FY2017year_end_exit_code, FY2013ACT_composite_score, FY2013ACT_english_score, FY2013ACT_reading_score, FY2013ACT_math_score, FY2013ACT_science_score, FY2015ACT_composite_score, FY2015ACT_english_score, FY2015ACT_reading_score, FY2015ACT_math_score, FY2015ACT_science_score, FY2016ACT_composite_score, FY2016ACT_english_score, FY2016ACT_reading_score, FY2016ACT_math_score, FY2016ACT_science_score, FY2017ACT_composite_score, FY2017ACT_english_score, FY2017ACT_reading_score, FY2017ACT_math_score, FY2017ACT_science_score, FY2018ACT_composite_score, FY2018ACT_english_score, FY2018ACT_reading_score, FY2018ACT_math_score, FY2018ACT_science_score, FY2014AIMS_science_score, FY2014AIMS_science_perf_level, FY2015AIMS_science_score, FY2015AIMS_science_perf_level, FY2016AIMS_science_score, FY2016AIMS_science_perf_level, FY2017AIMS_science_score, FY2017AIMS_science_perf_level, FY2018AIMS_science_score, FY2018AIMS_science_perf_level, FY2015AzMerit_ELA9_score, FY2015AzMerit_ELA9_perf_level, FY2015AzMerit_ELA10_score, FY2015AzMerit_ELA10_perf_level, FY2015AzMerit_ELA11_score, FY2015AzMerit_ELA11_perf_level, FY2015AzMerit_AlgI_score, FY2015AzMerit_AlgI_perf_level, ...]
Index: []

(68055, 803) (33023, 700) (38503, 837) (34785, 782) (76962, 712)

In [4]:
# Irene

# keep only one column about ethnicity for df1
df1['ethnicity'] = df1['ethnicity_recoded']
df1.drop(columns=df1.filter(regex=re.compile(r'ethnicity_|hispanic_indicator'), axis=1).columns, inplace=True)

# 'collegecoregpa', 'collegecoreclassrank' only exist in d1, so drop them
df1.drop(columns=df1.filter(regex=re.compile(r'.*(collegecoregpa|collegecoreclassrank)'), axis=1).columns, inplace=True)
df1.head(0)

Empty DataFrame
Columns: [study_id, district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2013grade_level, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2018grade_level, FY2014high_school_code1, FY2015high_school_code1, FY2016high_school_code1, FY2017high_school_code1, FY2019high_school_code1, FY2013gpa_school1, FY2014gpa_school1, FY2015gpa_school1, FY2016gpa_school1, FY2017gpa_school1, FY2018gpa_school1, FY2013days_absent_school1, FY2014days_absent_school1, FY2015days_absent_school1, FY2016days_absent_school1, FY2017days_absent_school1, FY2018days_absent_school1, FY2013unweightedclassrank_school1, FY2014unweightedclassrank_school1, FY2015unweightedclassrank_school1, FY2016unweightedclassrank_school1, FY2017unweightedclassrank_school1, FY2018unweightedclassrank_school1, FY2010ACT_composite_score, FY2010ACT_composite_perf_level, FY2010ACT_english_score, FY2010ACT_english_perf_level, FY2010ACT_reading_score, FY2010ACT_reading_perf_level, FY2010ACT_math_score, FY2010ACT_math_perf_level, FY2010ACT_science_score, FY2010ACT_science_perf_level, FY2012ACT_composite_score, FY2012ACT_composite_perf_level, FY2012ACT_english_score, FY2012ACT_english_perf_level, FY2012ACT_reading_score, FY2012ACT_reading_perf_level, FY2012ACT_math_score, FY2012ACT_math_perf_level, FY2012ACT_science_score, FY2012ACT_science_perf_level, FY2013ACT_composite_score, FY2013ACT_composite_perf_level, FY2013ACT_english_score, FY2013ACT_english_perf_level, FY2013ACT_reading_score, FY2013ACT_reading_perf_level, FY2013ACT_math_score, FY2013ACT_math_perf_level, FY2013ACT_science_score, FY2013ACT_science_perf_level, FY2014ACT_composite_score, FY2014ACT_composite_perf_level, FY2014ACT_english_score, FY2014ACT_english_perf_level, FY2014ACT_reading_score, FY2014ACT_reading_perf_level, FY2014ACT_math_score, FY2014ACT_math_perf_level, FY2014ACT_science_score, FY2014ACT_science_perf_level, FY2015ACT_composite_score, FY2015ACT_composite_perf_level, FY2015ACT_english_score, FY2015ACT_english_perf_level, FY2015ACT_reading_score, FY2015ACT_reading_perf_level, FY2015ACT_math_score, FY2015ACT_math_perf_level, FY2015ACT_science_score, FY2015ACT_science_perf_level, FY2016ACT_composite_score, FY2016ACT_composite_perf_level, FY2016ACT_english_score, FY2016ACT_english_perf_level, FY2016ACT_reading_score, FY2016ACT_reading_perf_level, FY2016ACT_math_score, FY2016ACT_math_perf_level, FY2016ACT_science_score, FY2016ACT_science_perf_level, FY2017ACT_composite_score, FY2017ACT_composite_perf_level, FY2017ACT_english_score, ...]
Index: []

In [5]:
# Irene

# drop all test & exam
exam_regex = re.compile(r'FY\d{4}[A-Z]+.*')

for df_name, df in df_l:
    
    df.set_index('study_id', inplace=True)
    df.drop(columns=df.filter(regex=exam_regex, axis=1).columns, inplace=True)    
    display(df.head(0))
    
print(df1.shape, df2.shape, df3.shape, df4.shape, df5.shape)

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2013grade_level, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2018grade_level, FY2014high_school_code1, FY2015high_school_code1, FY2016high_school_code1, FY2017high_school_code1, FY2019high_school_code1, FY2013gpa_school1, FY2014gpa_school1, FY2015gpa_school1, FY2016gpa_school1, FY2017gpa_school1, FY2018gpa_school1, FY2013days_absent_school1, FY2014days_absent_school1, FY2015days_absent_school1, FY2016days_absent_school1, FY2017days_absent_school1, FY2018days_absent_school1, FY2013unweightedclassrank_school1, FY2014unweightedclassrank_school1, FY2015unweightedclassrank_school1, FY2016unweightedclassrank_school1, FY2017unweightedclassrank_school1, FY2018unweightedclassrank_school1, high_school_grad_date, FY2014college1_begin_date, FY2014college1_end_date, FY2014college1_enrollment_status, FY2014college1_name, FY2014college1_type2or4year, FY2014college1_public_private, FY2014college2_begin_date, FY2014college2_end_date, FY2014college2_enrollment_status, FY2014college2_name, FY2014college2_type2or4year, FY2014college2_public_private, FY2014college3_begin_date, FY2014college3_end_date, FY2014college3_enrollment_status, FY2014college3_name, FY2014college3_type2or4year, FY2014college3_public_private, FY2014college4_begin_date, FY2014college4_end_date, FY2014college4_enrollment_status, FY2014college4_name, FY2014college4_type2or4year, FY2014college4_public_private, FY2014college5_begin_date, FY2014college5_end_date, FY2014college5_enrollment_status, FY2014college5_name, FY2014college5_type2or4year, FY2014college5_public_private, FY2014college6_begin_date, FY2014college6_end_date, FY2014college6_enrollment_status, FY2014college6_name, FY2014college6_type2or4year, FY2014college6_public_private, FY2015college1_begin_date, FY2015college1_end_date, FY2015college1_enrollment_status, FY2015college1_name, FY2015college1_type2or4year, FY2015college1_public_private, FY2015college2_begin_date, FY2015college2_end_date, FY2015college2_enrollment_status, FY2015college2_name, FY2015college2_type2or4year, FY2015college2_public_private, FY2015college3_begin_date, FY2015college3_end_date, FY2015college3_enrollment_status, FY2015college3_name, FY2015college3_type2or4year, FY2015college3_public_private, FY2015college4_begin_date, FY2015college4_end_date, FY2015college4_enrollment_status, FY2015college4_name, FY2015college4_type2or4year, FY2015college4_public_private, FY2015college5_begin_date, FY2015college5_end_date, FY2015college5_enrollment_status, ...]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2018grade_level, FY2014gpa_school1, FY2015gpa_school1, FY2016gpa_school1, FY2017gpa_school1, FY2018gpa_school1, high_school_grad_date, FY2014college1_begin_date, FY2014college1_end_date, FY2014college1_enrollment_status, FY2014college1_name, FY2014college1_type2or4year, FY2014college1_public_private, FY2014college2_begin_date, FY2014college2_end_date, FY2014college2_enrollment_status, FY2014college2_name, FY2014college2_type2or4year, FY2014college2_public_private, FY2014college3_begin_date, FY2014college3_end_date, FY2014college3_enrollment_status, FY2014college3_name, FY2014college3_type2or4year, FY2014college3_public_private, FY2014college4_begin_date, FY2014college4_end_date, FY2014college4_enrollment_status, FY2014college4_name, FY2014college4_type2or4year, FY2014college4_public_private, FY2014college5_begin_date, FY2014college5_end_date, FY2014college5_enrollment_status, FY2014college5_name, FY2014college5_type2or4year, FY2014college5_public_private, FY2014college6_begin_date, FY2014college6_end_date, FY2014college6_enrollment_status, FY2014college6_name, FY2014college6_type2or4year, FY2014college6_public_private, FY2014college7_begin_date, FY2014college7_end_date, FY2014college7_enrollment_status, FY2014college7_name, FY2014college7_type2or4year, FY2014college7_public_private, FY2015college1_begin_date, FY2015college1_end_date, FY2015college1_enrollment_status, FY2015college1_name, FY2015college1_type2or4year, FY2015college1_public_private, FY2015college2_begin_date, FY2015college2_end_date, FY2015college2_enrollment_status, FY2015college2_name, FY2015college2_type2or4year, FY2015college2_public_private, FY2015college3_begin_date, FY2015college3_end_date, FY2015college3_enrollment_status, FY2015college3_name, FY2015college3_type2or4year, FY2015college3_public_private, FY2015college4_begin_date, FY2015college4_end_date, FY2015college4_enrollment_status, FY2015college4_name, FY2015college4_type2or4year, FY2015college4_public_private, FY2015college5_begin_date, FY2015college5_end_date, FY2015college5_enrollment_status, FY2015college5_name, FY2015college5_type2or4year, FY2015college5_public_private, FY2015college6_begin_date, FY2015college6_end_date, FY2015college6_enrollment_status, FY2015college6_name, FY2015college6_type2or4year, FY2015college6_public_private, FY2016college1_begin_date, FY2016college1_end_date, FY2016college1_enrollment_status, FY2016college1_name, ...]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2018grade_level, FY2014high_school_code1, FY2014high_school_code2, FY2014high_school_code3, FY2015high_school_code1, FY2015high_school_code2, FY2016high_school_code1, FY2016high_school_code2, FY2017high_school_code1, FY2018high_school_code1, FY2014gpa_school1, FY2014gpa_school2, FY2014gpa_school3, FY2015gpa_school1, FY2015gpa_school2, FY2016gpa_school1, FY2016gpa_school2, FY2017gpa_school1, FY2018gpa_school1, FY2014unweightedclassrank_school1, FY2014unweightedclassrank_school2, FY2014unweightedclassrank_school3, FY2015unweightedclassrank_school1, FY2015unweightedclassrank_school2, FY2016unweightedclassrank_school1, FY2016unweightedclassrank_school2, FY2017unweightedclassrank_school1, FY2018unweightedclassrank_school1, high_school_grad_date, FY2011college1_begin_date, FY2011college1_end_date, FY2011college1_enrollment_status, FY2011college1_name, FY2011college1_type2or4year, FY2011college1_public_private, FY2011college2_begin_date, FY2011college2_end_date, FY2011college2_enrollment_status, FY2011college2_name, FY2011college2_type2or4year, FY2011college2_public_private, FY2011college3_begin_date, FY2011college3_end_date, FY2011college3_enrollment_status, FY2011college3_name, FY2011college3_type2or4year, FY2011college3_public_private, FY2011college4_begin_date, FY2011college4_end_date, FY2011college4_enrollment_status, FY2011college4_name, FY2011college4_type2or4year, FY2011college4_public_private, FY2011college5_begin_date, FY2011college5_end_date, FY2011college5_enrollment_status, FY2011college5_name, FY2011college5_type2or4year, FY2011college5_public_private, FY2011college6_begin_date, FY2011college6_end_date, FY2011college6_enrollment_status, FY2011college6_name, FY2011college6_type2or4year, FY2011college6_public_private, FY2011college7_begin_date, FY2011college7_end_date, FY2011college7_enrollment_status, FY2011college7_name, FY2011college7_type2or4year, FY2011college7_public_private, FY2012college1_begin_date, FY2012college1_end_date, FY2012college1_enrollment_status, FY2012college1_name, FY2012college1_type2or4year, FY2012college1_public_private, FY2012college2_begin_date, FY2012college2_end_date, FY2012college2_enrollment_status, FY2012college2_name, FY2012college2_type2or4year, FY2012college2_public_private, FY2012college3_begin_date, FY2012college3_end_date, FY2012college3_enrollment_status, FY2012college3_name, FY2012college3_type2or4year, FY2012college3_public_private, ...]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2014high_school_code1, FY2014high_school_code2, FY2014high_school_code3, FY2015high_school_code1, FY2015high_school_code2, FY2015high_school_code3, FY2016high_school_code1, FY2016high_school_code2, FY2016high_school_code3, FY2017high_school_code1, FY2017high_school_code2, FY2017high_school_code3, FY2014days_absent_school1, FY2014days_absent_school2, FY2014days_absent_school3, FY2015days_absent_school1, FY2015days_absent_school2, FY2015days_absent_school3, FY2016days_absent_school1, FY2016days_absent_school2, FY2016days_absent_school3, FY2017days_absent_school1, FY2017days_absent_school2, FY2017days_absent_school3, high_school_grad_date, FY2009college1_begin_date, FY2009college1_end_date, FY2009college1_enrollment_status, FY2009college1_name, FY2009college1_type2or4year, FY2009college1_public_private, FY2009college2_begin_date, FY2009college2_end_date, FY2009college2_enrollment_status, FY2009college2_name, FY2009college2_type2or4year, FY2009college2_public_private, FY2010college1_begin_date, FY2010college1_end_date, FY2010college1_enrollment_status, FY2010college1_name, FY2010college1_type2or4year, FY2010college1_public_private, FY2010college2_begin_date, FY2010college2_end_date, FY2010college2_enrollment_status, FY2010college2_name, FY2010college2_type2or4year, FY2010college2_public_private, FY2010college3_begin_date, FY2010college3_end_date, FY2010college3_enrollment_status, FY2010college3_name, FY2010college3_type2or4year, FY2010college3_public_private, FY2010college4_begin_date, FY2010college4_end_date, FY2010college4_enrollment_status, FY2010college4_name, FY2010college4_type2or4year, FY2010college4_public_private, FY2010college5_begin_date, FY2010college5_end_date, FY2010college5_enrollment_status, FY2010college5_name, FY2010college5_type2or4year, FY2010college5_public_private, FY2010college6_begin_date, FY2010college6_end_date, FY2010college6_enrollment_status, FY2010college6_name, FY2010college6_type2or4year, FY2010college6_public_private, FY2010college7_begin_date, FY2010college7_end_date, FY2010college7_enrollment_status, FY2010college7_name, FY2010college7_type2or4year, FY2010college7_public_private, FY2010college8_begin_date, FY2010college8_end_date, FY2010college8_enrollment_status, FY2010college8_name, FY2010college8_type2or4year, FY2010college8_public_private, FY2010college9_begin_date, FY2010college9_end_date, FY2010college9_enrollment_status, FY2010college9_name, ...]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, FY2013grade_level, FY2014grade_level, FY2015grade_level, FY2016grade_level, FY2017grade_level, FY2013high_school_code1, FY2013high_school_code2, FY2013high_school_code3, FY2014high_school_code1, FY2014high_school_code2, FY2014high_school_code3, FY2015high_school_code1, FY2015high_school_code2, FY2015high_school_code3, FY2015high_school_code4, FY2016high_school_code1, FY2016high_school_code2, FY2016high_school_code3, FY2017high_school_code1, FY2017high_school_code2, FY2017high_school_code3, FY2017high_school_code4, FY2013gpa_school1, FY2014gpa_school1, FY2015gpa_school1, FY2016gpa_school1, FY2017gpa_school1, FY2013days_absent_school1, FY2013days_absent_school2, FY2013days_absent_school3, FY2014days_absent_school1, FY2014days_absent_school2, FY2014days_absent_school3, FY2015days_absent_school1, FY2015days_absent_school2, FY2015days_absent_school3, FY2015days_absent_school4, FY2016days_absent_school1, FY2016days_absent_school2, FY2016days_absent_school3, FY2017days_absent_school1, FY2017days_absent_school2, FY2017days_absent_school3, FY2017days_absent_school4, FY2013year_end_exit_code, FY2014year_end_exit_code, FY2015year_end_exit_code, FY2016year_end_exit_code, FY2017year_end_exit_code, high_school_grad_date, FY2011college1_begin_date, FY2011college1_end_date, FY2011college1_enrollment_status, FY2011college1_name, FY2011college1_type2or4year, FY2011college1_public_private, FY2011college2_begin_date, FY2011college2_end_date, FY2011college2_enrollment_status, FY2011college2_name, FY2011college2_type2or4year, FY2011college2_public_private, FY2011college3_begin_date, FY2011college3_end_date, FY2011college3_enrollment_status, FY2011college3_name, FY2011college3_type2or4year, FY2011college3_public_private, FY2011college4_begin_date, FY2011college4_end_date, FY2011college4_enrollment_status, FY2011college4_name, FY2011college4_type2or4year, FY2011college4_public_private, FY2011college5_begin_date, FY2011college5_end_date, FY2011college5_enrollment_status, FY2011college5_name, FY2011college5_type2or4year, FY2011college5_public_private, FY2011college6_begin_date, FY2011college6_end_date, FY2011college6_enrollment_status, FY2011college6_name, FY2011college6_type2or4year, FY2011college6_public_private, FY2011college7_begin_date, FY2011college7_end_date, FY2011college7_enrollment_status, FY2011college7_name, FY2011college7_type2or4year, FY2011college7_public_private, FY2011college8_begin_date, ...]
Index: []

(68055, 292) (33023, 259) (38503, 579) (34785, 711) (76962, 628)

In [6]:
# Irene

# construct dataframe about the student's basic info, college status related info, high school related info
info_regex = re.compile(r'^(?!(FY\d{4}|college)).+')
college_regex = re.compile(r'college')

for df_name, df in df_l:
    dfd = df_d[df_name]
    #df.drop(columns='birth_date', inplace=True)
    dfd['info'] = df.filter(regex=info_regex, axis=1).copy()
    dfd['college'] = df.filter(regex=college_regex, axis=1).copy()
    
    cols = list(dfd['info'].columns) + list(dfd['college'].columns)
    dfd['high_school'] = df[set(df.columns) - set(cols)].copy()
    
    display(dfd['info'].head(0))
    display(dfd['college'].head(0))
    display(dfd['high_school'].head(0))

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, high_school_grad_date]
Index: []

Empty DataFrame
Columns: [FY2014college1_begin_date, FY2014college1_end_date, FY2014college1_enrollment_status, FY2014college1_name, FY2014college1_type2or4year, FY2014college1_public_private, FY2014college2_begin_date, FY2014college2_end_date, FY2014college2_enrollment_status, FY2014college2_name, FY2014college2_type2or4year, FY2014college2_public_private, FY2014college3_begin_date, FY2014college3_end_date, FY2014college3_enrollment_status, FY2014college3_name, FY2014college3_type2or4year, FY2014college3_public_private, FY2014college4_begin_date, FY2014college4_end_date, FY2014college4_enrollment_status, FY2014college4_name, FY2014college4_type2or4year, FY2014college4_public_private, FY2014college5_begin_date, FY2014college5_end_date, FY2014college5_enrollment_status, FY2014college5_name, FY2014college5_type2or4year, FY2014college5_public_private, FY2014college6_begin_date, FY2014college6_end_date, FY2014college6_enrollment_status, FY2014college6_name, FY2014college6_type2or4year, FY2014college6_public_private, FY2015college1_begin_date, FY2015college1_end_date, FY2015college1_enrollment_status, FY2015college1_name, FY2015college1_type2or4year, FY2015college1_public_private, FY2015college2_begin_date, FY2015college2_end_date, FY2015college2_enrollment_status, FY2015college2_name, FY2015college2_type2or4year, FY2015college2_public_private, FY2015college3_begin_date, FY2015college3_end_date, FY2015college3_enrollment_status, FY2015college3_name, FY2015college3_type2or4year, FY2015college3_public_private, FY2015college4_begin_date, FY2015college4_end_date, FY2015college4_enrollment_status, FY2015college4_name, FY2015college4_type2or4year, FY2015college4_public_private, FY2015college5_begin_date, FY2015college5_end_date, FY2015college5_enrollment_status, FY2015college5_name, FY2015college5_type2or4year, FY2015college5_public_private, FY2015college6_begin_date, FY2015college6_end_date, FY2015college6_enrollment_status, FY2015college6_name, FY2015college6_type2or4year, FY2015college6_public_private, FY2015college7_begin_date, FY2015college7_end_date, FY2015college7_enrollment_status, FY2015college7_name, FY2015college7_type2or4year, FY2015college7_public_private, FY2015college8_begin_date, FY2015college8_end_date, FY2015college8_enrollment_status, FY2015college8_name, FY2015college8_type2or4year, FY2015college8_public_private, FY2015college9_begin_date, FY2015college9_end_date, FY2015college9_enrollment_status, FY2015college9_name, FY2015college9_type2or4year, FY2015college9_public_private, FY2015college10_begin_date, FY2015college10_end_date, FY2015college10_enrollment_status, FY2015college10_name, FY2015college10_type2or4year, FY2015college10_public_private, FY2016college1_begin_date, FY2016college1_end_date, FY2016college1_enrollment_status, FY2016college1_name, ...]
Index: []

Empty DataFrame
Columns: [FY2018grade_level, FY2018gpa_school1, FY2017gpa_school1, FY2014days_absent_school1, FY2014high_school_code1, FY2014unweightedclassrank_school1, FY2017high_school_code1, FY2017days_absent_school1, FY2013days_absent_school1, FY2013unweightedclassrank_school1, FY2013gpa_school1, FY2016high_school_code1, FY2015grade_level, FY2016gpa_school1, FY2014gpa_school1, FY2015unweightedclassrank_school1, FY2014grade_level, FY2015days_absent_school1, FY2016unweightedclassrank_school1, FY2015gpa_school1, FY2016days_absent_school1, FY2016grade_level, FY2018unweightedclassrank_school1, FY2018days_absent_school1, FY2019high_school_code1, FY2017unweightedclassrank_school1, FY2017grade_level, FY2015high_school_code1, FY2013grade_level]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, high_school_grad_date]
Index: []

Empty DataFrame
Columns: [FY2014college1_begin_date, FY2014college1_end_date, FY2014college1_enrollment_status, FY2014college1_name, FY2014college1_type2or4year, FY2014college1_public_private, FY2014college2_begin_date, FY2014college2_end_date, FY2014college2_enrollment_status, FY2014college2_name, FY2014college2_type2or4year, FY2014college2_public_private, FY2014college3_begin_date, FY2014college3_end_date, FY2014college3_enrollment_status, FY2014college3_name, FY2014college3_type2or4year, FY2014college3_public_private, FY2014college4_begin_date, FY2014college4_end_date, FY2014college4_enrollment_status, FY2014college4_name, FY2014college4_type2or4year, FY2014college4_public_private, FY2014college5_begin_date, FY2014college5_end_date, FY2014college5_enrollment_status, FY2014college5_name, FY2014college5_type2or4year, FY2014college5_public_private, FY2014college6_begin_date, FY2014college6_end_date, FY2014college6_enrollment_status, FY2014college6_name, FY2014college6_type2or4year, FY2014college6_public_private, FY2014college7_begin_date, FY2014college7_end_date, FY2014college7_enrollment_status, FY2014college7_name, FY2014college7_type2or4year, FY2014college7_public_private, FY2015college1_begin_date, FY2015college1_end_date, FY2015college1_enrollment_status, FY2015college1_name, FY2015college1_type2or4year, FY2015college1_public_private, FY2015college2_begin_date, FY2015college2_end_date, FY2015college2_enrollment_status, FY2015college2_name, FY2015college2_type2or4year, FY2015college2_public_private, FY2015college3_begin_date, FY2015college3_end_date, FY2015college3_enrollment_status, FY2015college3_name, FY2015college3_type2or4year, FY2015college3_public_private, FY2015college4_begin_date, FY2015college4_end_date, FY2015college4_enrollment_status, FY2015college4_name, FY2015college4_type2or4year, FY2015college4_public_private, FY2015college5_begin_date, FY2015college5_end_date, FY2015college5_enrollment_status, FY2015college5_name, FY2015college5_type2or4year, FY2015college5_public_private, FY2015college6_begin_date, FY2015college6_end_date, FY2015college6_enrollment_status, FY2015college6_name, FY2015college6_type2or4year, FY2015college6_public_private, FY2016college1_begin_date, FY2016college1_end_date, FY2016college1_enrollment_status, FY2016college1_name, FY2016college1_type2or4year, FY2016college1_public_private, FY2016college2_begin_date, FY2016college2_end_date, FY2016college2_enrollment_status, FY2016college2_name, FY2016college2_type2or4year, FY2016college2_public_private, FY2016college3_begin_date, FY2016college3_end_date, FY2016college3_enrollment_status, FY2016college3_name, FY2016college3_type2or4year, FY2016college3_public_private, FY2016college4_begin_date, FY2016college4_end_date, FY2016college4_enrollment_status, FY2016college4_name, ...]
Index: []

Empty DataFrame
Columns: [FY2018grade_level, FY2018gpa_school1, FY2017gpa_school1, FY2015grade_level, FY2015gpa_school1, FY2016gpa_school1, FY2017grade_level, FY2014gpa_school1, FY2016grade_level, FY2014grade_level]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, high_school_grad_date]
Index: []

Empty DataFrame
Columns: [FY2011college1_begin_date, FY2011college1_end_date, FY2011college1_enrollment_status, FY2011college1_name, FY2011college1_type2or4year, FY2011college1_public_private, FY2011college2_begin_date, FY2011college2_end_date, FY2011college2_enrollment_status, FY2011college2_name, FY2011college2_type2or4year, FY2011college2_public_private, FY2011college3_begin_date, FY2011college3_end_date, FY2011college3_enrollment_status, FY2011college3_name, FY2011college3_type2or4year, FY2011college3_public_private, FY2011college4_begin_date, FY2011college4_end_date, FY2011college4_enrollment_status, FY2011college4_name, FY2011college4_type2or4year, FY2011college4_public_private, FY2011college5_begin_date, FY2011college5_end_date, FY2011college5_enrollment_status, FY2011college5_name, FY2011college5_type2or4year, FY2011college5_public_private, FY2011college6_begin_date, FY2011college6_end_date, FY2011college6_enrollment_status, FY2011college6_name, FY2011college6_type2or4year, FY2011college6_public_private, FY2011college7_begin_date, FY2011college7_end_date, FY2011college7_enrollment_status, FY2011college7_name, FY2011college7_type2or4year, FY2011college7_public_private, FY2012college1_begin_date, FY2012college1_end_date, FY2012college1_enrollment_status, FY2012college1_name, FY2012college1_type2or4year, FY2012college1_public_private, FY2012college2_begin_date, FY2012college2_end_date, FY2012college2_enrollment_status, FY2012college2_name, FY2012college2_type2or4year, FY2012college2_public_private, FY2012college3_begin_date, FY2012college3_end_date, FY2012college3_enrollment_status, FY2012college3_name, FY2012college3_type2or4year, FY2012college3_public_private, FY2012college4_begin_date, FY2012college4_end_date, FY2012college4_enrollment_status, FY2012college4_name, FY2012college4_type2or4year, FY2012college4_public_private, FY2012college5_begin_date, FY2012college5_end_date, FY2012college5_enrollment_status, FY2012college5_name, FY2012college5_type2or4year, FY2012college5_public_private, FY2012college6_begin_date, FY2012college6_end_date, FY2012college6_enrollment_status, FY2012college6_name, FY2012college6_type2or4year, FY2012college6_public_private, FY2012college7_begin_date, FY2012college7_end_date, FY2012college7_enrollment_status, FY2012college7_name, FY2012college7_type2or4year, FY2012college7_public_private, FY2012college8_begin_date, FY2012college8_end_date, FY2012college8_enrollment_status, FY2012college8_name, FY2012college8_type2or4year, FY2012college8_public_private, FY2012college9_begin_date, FY2012college9_end_date, FY2012college9_enrollment_status, FY2012college9_name, FY2012college9_type2or4year, FY2012college9_public_private, FY2012college10_begin_date, FY2012college10_end_date, FY2012college10_enrollment_status, FY2012college10_name, ...]
Index: []

Empty DataFrame
Columns: [FY2018grade_level, FY2018gpa_school1, FY2016gpa_school2, FY2017gpa_school1, FY2014unweightedclassrank_school2, FY2014high_school_code1, FY2014gpa_school2, FY2014unweightedclassrank_school1, FY2017high_school_code1, FY2016high_school_code1, FY2015grade_level, FY2016gpa_school1, FY2014gpa_school1, FY2018high_school_code1, FY2015unweightedclassrank_school1, FY2014unweightedclassrank_school3, FY2014grade_level, FY2016unweightedclassrank_school1, FY2015gpa_school1, FY2014gpa_school3, FY2015unweightedclassrank_school2, FY2016grade_level, FY2018unweightedclassrank_school1, FY2015high_school_code2, FY2016high_school_code2, FY2014high_school_code3, FY2017unweightedclassrank_school1, FY2017grade_level, FY2015high_school_code1, FY2016unweightedclassrank_school2, FY2014high_school_code2, FY2015gpa_school2]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, high_school_grad_date]
Index: []

Empty DataFrame
Columns: [FY2009college1_begin_date, FY2009college1_end_date, FY2009college1_enrollment_status, FY2009college1_name, FY2009college1_type2or4year, FY2009college1_public_private, FY2009college2_begin_date, FY2009college2_end_date, FY2009college2_enrollment_status, FY2009college2_name, FY2009college2_type2or4year, FY2009college2_public_private, FY2010college1_begin_date, FY2010college1_end_date, FY2010college1_enrollment_status, FY2010college1_name, FY2010college1_type2or4year, FY2010college1_public_private, FY2010college2_begin_date, FY2010college2_end_date, FY2010college2_enrollment_status, FY2010college2_name, FY2010college2_type2or4year, FY2010college2_public_private, FY2010college3_begin_date, FY2010college3_end_date, FY2010college3_enrollment_status, FY2010college3_name, FY2010college3_type2or4year, FY2010college3_public_private, FY2010college4_begin_date, FY2010college4_end_date, FY2010college4_enrollment_status, FY2010college4_name, FY2010college4_type2or4year, FY2010college4_public_private, FY2010college5_begin_date, FY2010college5_end_date, FY2010college5_enrollment_status, FY2010college5_name, FY2010college5_type2or4year, FY2010college5_public_private, FY2010college6_begin_date, FY2010college6_end_date, FY2010college6_enrollment_status, FY2010college6_name, FY2010college6_type2or4year, FY2010college6_public_private, FY2010college7_begin_date, FY2010college7_end_date, FY2010college7_enrollment_status, FY2010college7_name, FY2010college7_type2or4year, FY2010college7_public_private, FY2010college8_begin_date, FY2010college8_end_date, FY2010college8_enrollment_status, FY2010college8_name, FY2010college8_type2or4year, FY2010college8_public_private, FY2010college9_begin_date, FY2010college9_end_date, FY2010college9_enrollment_status, FY2010college9_name, FY2010college9_type2or4year, FY2010college9_public_private, FY2011college1_begin_date, FY2011college1_end_date, FY2011college1_enrollment_status, FY2011college1_name, FY2011college1_type2or4year, FY2011college1_public_private, FY2011college2_begin_date, FY2011college2_end_date, FY2011college2_enrollment_status, FY2011college2_name, FY2011college2_type2or4year, FY2011college2_public_private, FY2011college3_begin_date, FY2011college3_end_date, FY2011college3_enrollment_status, FY2011college3_name, FY2011college3_type2or4year, FY2011college3_public_private, FY2011college4_begin_date, FY2011college4_end_date, FY2011college4_enrollment_status, FY2011college4_name, FY2011college4_type2or4year, FY2011college4_public_private, FY2011college5_begin_date, FY2011college5_end_date, FY2011college5_enrollment_status, FY2011college5_name, FY2011college5_type2or4year, FY2011college5_public_private, FY2011college6_begin_date, FY2011college6_end_date, FY2011college6_enrollment_status, FY2011college6_name, ...]
Index: []

Empty DataFrame
Columns: [FY2014days_absent_school1, FY2017days_absent_school3, FY2014days_absent_school3, FY2014high_school_code1, FY2017high_school_code1, FY2017days_absent_school1, FY2015high_school_code3, FY2016high_school_code1, FY2015grade_level, FY2015days_absent_school3, FY2017high_school_code2, FY2014grade_level, FY2015days_absent_school1, FY2017high_school_code3, FY2016days_absent_school3, FY2016days_absent_school1, FY2016grade_level, FY2015high_school_code2, FY2016high_school_code2, FY2014high_school_code3, FY2016days_absent_school2, FY2017days_absent_school2, FY2017grade_level, FY2015high_school_code1, FY2016high_school_code3, FY2014high_school_code2, FY2015days_absent_school2, FY2014days_absent_school2]
Index: []

Empty DataFrame
Columns: [district, birth_date, gender, ethnicity, ell_indicator, sped_indicator, free_reduced_lunch_indicator, high_school_grad_date]
Index: []

Empty DataFrame
Columns: [FY2011college1_begin_date, FY2011college1_end_date, FY2011college1_enrollment_status, FY2011college1_name, FY2011college1_type2or4year, FY2011college1_public_private, FY2011college2_begin_date, FY2011college2_end_date, FY2011college2_enrollment_status, FY2011college2_name, FY2011college2_type2or4year, FY2011college2_public_private, FY2011college3_begin_date, FY2011college3_end_date, FY2011college3_enrollment_status, FY2011college3_name, FY2011college3_type2or4year, FY2011college3_public_private, FY2011college4_begin_date, FY2011college4_end_date, FY2011college4_enrollment_status, FY2011college4_name, FY2011college4_type2or4year, FY2011college4_public_private, FY2011college5_begin_date, FY2011college5_end_date, FY2011college5_enrollment_status, FY2011college5_name, FY2011college5_type2or4year, FY2011college5_public_private, FY2011college6_begin_date, FY2011college6_end_date, FY2011college6_enrollment_status, FY2011college6_name, FY2011college6_type2or4year, FY2011college6_public_private, FY2011college7_begin_date, FY2011college7_end_date, FY2011college7_enrollment_status, FY2011college7_name, FY2011college7_type2or4year, FY2011college7_public_private, FY2011college8_begin_date, FY2011college8_end_date, FY2011college8_enrollment_status, FY2011college8_name, FY2011college8_type2or4year, FY2011college8_public_private, FY2012college1_begin_date, FY2012college1_end_date, FY2012college1_enrollment_status, FY2012college1_name, FY2012college1_type2or4year, FY2012college1_public_private, FY2012college2_begin_date, FY2012college2_end_date, FY2012college2_enrollment_status, FY2012college2_name, FY2012college2_type2or4year, FY2012college2_public_private, FY2012college3_begin_date, FY2012college3_end_date, FY2012college3_enrollment_status, FY2012college3_name, FY2012college3_type2or4year, FY2012college3_public_private, FY2012college4_begin_date, FY2012college4_end_date, FY2012college4_enrollment_status, FY2012college4_name, FY2012college4_type2or4year, FY2012college4_public_private, FY2012college5_begin_date, FY2012college5_end_date, FY2012college5_enrollment_status, FY2012college5_name, FY2012college5_type2or4year, FY2012college5_public_private, FY2012college6_begin_date, FY2012college6_end_date, FY2012college6_enrollment_status, FY2012college6_name, FY2012college6_type2or4year, FY2012college6_public_private, FY2012college7_begin_date, FY2012college7_end_date, FY2012college7_enrollment_status, FY2012college7_name, FY2012college7_type2or4year, FY2012college7_public_private, FY2012college8_begin_date, FY2012college8_end_date, FY2012college8_enrollment_status, FY2012college8_name, FY2012college8_type2or4year, FY2012college8_public_private, FY2012college9_begin_date, FY2012college9_end_date, FY2012college9_enrollment_status, FY2012college9_name, ...]
Index: []

Empty DataFrame
Columns: [FY2017gpa_school1, FY2014days_absent_school1, FY2014year_end_exit_code, FY2017days_absent_school3, FY2014days_absent_school3, FY2017high_school_code4, FY2015days_absent_school4, FY2014high_school_code1, FY2017high_school_code1, FY2017days_absent_school1, FY2013days_absent_school1, FY2015high_school_code3, FY2013gpa_school1, FY2013days_absent_school2, FY2016high_school_code1, FY2015grade_level, FY2015days_absent_school3, FY2016gpa_school1, FY2014gpa_school1, FY2017high_school_code2, FY2013high_school_code1, FY2014grade_level, FY2015days_absent_school1, FY2013days_absent_school3, FY2013high_school_code2, FY2013high_school_code3, FY2017high_school_code3, FY2015year_end_exit_code, FY2015gpa_school1, FY2016days_absent_school3, FY2016days_absent_school1, FY2013year_end_exit_code, FY2016grade_level, FY2017days_absent_school4, FY2015high_school_code2, FY2016high_school_code2, FY2016year_end_exit_code, FY2014high_school_code3, FY2015high_school_code4, FY2013grade_level, FY2016days_absent_school2, FY2017days_absent_school2, FY2017grade_level, FY2015high_school_code1, FY2016high_school_code3, FY2017year_end_exit_code, FY2014high_school_code2, FY2015days_absent_school2, FY2014days_absent_school2]
Index: []

In [7]:
# Irene

# find the latest year of college info for each district
for df_name, df in df_l:
    dfd = df_d[df_name]
    FY_cols = dfd['college'].filter(regex=re.compile(r'FY\d{4}college.*')).columns
    df_d[df_name]['latest_year'] = int(max(set([i[2:6] for i in FY_cols])))
    display(df_d[df_name]['latest_year'])

2019

2018

2018

2019

2018

In [8]:
# Irene

# find the earliest year of college info for each district
for df_name, df in df_l:
    dfd = df_d[df_name]
    FY_cols = dfd['college'].filter(regex=re.compile(r'FY\d{4}college.*')).columns
    df_d[df_name]['earliest_year'] = int(min(set([i[2:6] for i in FY_cols])))
    display(df_d[df_name]['earliest_year'])

2014

2014

2011

2009

2011

#### **2. Get Student's Basic Info** 
[(→)](#Summary)

In [9]:
# Irene

# find the grade_level info for each district
for df_name, df in df_l:
    df_d[df_name]['grade_level'] = df_d[df_name]['high_school'].filter(regex=re.compile(r'FY\d{4}grade_level'), axis=1).copy()
    print(list(df_d[df_name]['grade_level'].columns))

['FY2018grade_level', 'FY2015grade_level', 'FY2014grade_level', 'FY2016grade_level', 'FY2017grade_level', 'FY2013grade_level']
['FY2018grade_level', 'FY2015grade_level', 'FY2017grade_level', 'FY2016grade_level', 'FY2014grade_level']
['FY2018grade_level', 'FY2015grade_level', 'FY2014grade_level', 'FY2016grade_level', 'FY2017grade_level']
['FY2015grade_level', 'FY2014grade_level', 'FY2016grade_level', 'FY2017grade_level']
['FY2015grade_level', 'FY2014grade_level', 'FY2016grade_level', 'FY2013grade_level', 'FY2017grade_level']

In [10]:
# Irene

# a function that can calculate the 9th grade year of students if they have at least one grade_level record
# -1 will be returned if there's no grade_level record
def year_level(x):
    if x.notna().sum() == 0:
        return -1
    else:
        grade = x[x.notna()].copy()
        if 9 in grade.values:
            grade9year = list(grade.index[grade.values==9])[0][2:6]
            return grade9year
        else:
            grade = sorted(tuple(zip(grade.index, grade.values)), key=lambda x: (x[0], x[1]))[0]
            grade9year = int(grade[0][2:6]) - (grade[1] - 9)
            return grade9year

In [11]:
# Irene

# student_info will store all the information needed for regression analysis
# find the 9th grade year of every student
for df_name, df in df_l:
    dfd = df_d[df_name]
    dfd['student_info'] = pd.DataFrame(index=dfd['grade_level'].index)
    dfd['student_info']['grade9year'] = dfd['grade_level'].apply(year_level, axis=1).astype(np.int16)
    if df_name == 'df4':
        print(df_name)
        dfd['student_info']['grade9year'] = dfd['student_info']['grade9year'].transform(lambda x: x + 1 if x != -1 else x)
    display(dfd['student_info'].head())
    print(dfd['student_info'][dfd['student_info'].grade9year==-1].shape)

           grade9year
study_id
111152.00        2017
111154.00        2015
111158.00        2017
111172.00        2016
111178.00        2018

(2599, 1)

          grade9year
study_id
1113631         2011
1119371         2011
1119961         2012
1161336         2012
1161776         2011

(51, 1)

           grade9year
study_id
102966224        2016
102966226        2016
102966229        2016
102966242        2016
102966244        2016

(7943, 1)
df4

            grade9year
study_id
2222173334          -1
2222173335          -1
2222173339          -1
2222173344          -1
2222173349          -1

(20177, 1)

          grade9year
study_id
4420444           -1
4422444           -1
41523444          -1
41822444          -1
41825444          -1

(18342, 1)

In [12]:
# Irene

# a function that can impute the 9th grade year based on birthdate
# if birth month is greater than 9, the 9th grade year will be birth year + 15, else will be + 14
def birthdate_impute(x):
    return_list = []
    for i in x:
        m = pd.DatetimeIndex([i]).month
        y = pd.DatetimeIndex([i]).year
        if m >= 9:
            return_list.append(y + 15)
        else:
            return_list.append(y + 14)
    return return_list

In [13]:
# Irene

# add some basic information about the students and indicators to student_info
for df_name, df in df_l:
    dfd = df_d[df_name]
    
    student_info = dfd['student_info']
    college_grad = dfd['college']
    
    student_info[dfd['info'].columns[0:-1]] = dfd['info'].iloc[:, 0:-1]
    
    # distinguish if the student graduated from high school
    # 1 = graduated from high school, 0 = didn't graduate or doesn't have data (like maybe transfer to other state)
    student_info['high_school_grad'] = dfd['info']['high_school_grad_date'].notna().transform(lambda x: 1 if x == True else 0)
    grad_index = student_info[student_info['high_school_grad']==1].index
    
    # for gradelevel is unknown, find the graduate date or birth date and calualate which year the student was on grade 9
    unknown9grade_index = student_info[student_info['grade9year'] == -1].index
    unknown9grade = dfd['info'].loc[unknown9grade_index]
    impute9grade_index = unknown9grade[unknown9grade['high_school_grad_date'].notna()].index
    student_info.loc[impute9grade_index, 'grade9year'] = pd.DatetimeIndex(dfd['info'].loc[impute9grade_index, 'high_school_grad_date']).year - 3
    
    unknown9grade_index = student_info[student_info['grade9year'] == -1].index
    unknown9grade = dfd['info'].loc[unknown9grade_index]
    impute9grade_index = unknown9grade[unknown9grade['birth_date'].notna()].index
    student_info.loc[impute9grade_index, 'grade9year'] = dfd['info'].loc[impute9grade_index, 'birth_date'].transform(birthdate_impute)
    
    # distinguish if the student is still studying in high school
    # 1 = still in high school, 0 = not in high school
    student_info['high_school_studying'] = 0 
    not_grad_index = student_info[~(student_info.index.isin(grad_index))].index
    high_school_studying_index = dfd['info'].loc[not_grad_index][student_info.loc[not_grad_index, 'grade9year'] + 3 > dfd['latest_year']].index
    student_info.loc[high_school_studying_index, 'high_school_studying'] = 1

    
    # distinguish if the student enrolled in college
    student_info['college_enroll'] = 0
    student_info['college_enroll'] = dfd['college'].filter(regex=re.compile(r'FY\d{4}college\d.*')).notna().sum(axis=1).transform(lambda x: 1 if x > 0 else 0)
    
    # distinguish if the student graduated from college
    student_info['college_graduate'] = dfd['college'].filter(regex=re.compile(r'college_grad.*')).notna().sum(axis=1).transform(lambda x: 1 if x > 0 else 0)

    # distinguish if the student is still studying in college
    # this part will be processed in later cell
    student_info['college_studying'] = 0
    
    if df_name not in ['df1', 'df2', 'df5']:
#         student_info['free_reduced_lunch_indicator'] = student_info['free_reduced_lunch_indicator'].fillna(-1).astype(np.int8)
        pass
    else:
        student_info['free_reduced_lunch_indicator'] = student_info['free_reduced_lunch_indicator'].fillna(0).astype(np.int8)
        
    display(student_info.head())

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying
study_id,,,,,,,,,,,,,
111152.00,2017,1,2002-10-25,F,Hispanic/Latino,0,0,1,0,1,0,0,0
111154.00,2015,1,2001-03-20,F,Hispanic/Latino,0,0,0,0,0,0,0,0
111158.00,2017,1,2003-03-27,F,Black/African American,0,0,1,0,1,0,0,0
111172.00,2016,1,2001-12-11,F,Hispanic/Latino,0,1,0,0,0,0,0,0
111178.00,2018,1,2004-05-12,F,Hispanic/Latino,1,0,1,0,1,0,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying
study_id,,,,,,,,,,,,,
1113631,2011,2,01/23/1996,F,Hispanic/Latino,0,0,0,1,0,1,0,0
1119371,2011,2,03/29/1996,F,White,0,0,1,0,0,0,0,0
1119961,2012,2,04/21/1996,M,Hispanic/Latino,0,0,0,0,0,0,0,0
1161336,2012,2,11/30/1996,M,Hispanic/Latino,0,0,0,1,0,1,1,0
1161776,2011,2,12/24/1995,F,Hispanic/Latino,0,0,0,0,0,0,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying
study_id,,,,,,,,,,,,,
102966224,2016,3,2001-03-23,F,Two or More,0,0,nan,0,1,0,0,0
102966226,2016,3,2001-02-02,M,Hispanic/Latino,0,0,nan,0,1,0,0,0
102966229,2016,3,2001-04-02,M,White,0,0,nan,0,1,0,0,0
102966242,2016,3,2001-10-30,M,Black/African American,0,0,nan,0,1,0,0,0
102966244,2016,3,2001-04-04,F,White,0,0,nan,0,1,0,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying
study_id,,,,,,,,,,,,,
2222173334,2006,4,None,None,None,0,0,nan,1,0,1,0,0
2222173335,2006,4,None,None,None,0,0,nan,1,0,1,0,0
2222173339,2006,4,None,None,None,0,0,nan,1,0,1,1,0
2222173344,2006,4,None,None,None,0,0,nan,1,0,1,0,0
2222173349,2006,4,None,None,None,0,0,nan,1,0,1,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying
study_id,,,,,,,,,,,,,
4420444,2008,5,None,None,None,0,0,0,1,0,1,1,0
4422444,2008,5,None,None,None,0,0,0,1,0,1,0,0
41523444,2009,5,None,None,None,0,0,0,1,0,1,1,0
41822444,2009,5,None,None,None,0,0,0,1,0,1,0,0
41825444,2009,5,None,None,None,0,0,0,1,0,1,1,0

#### **3. Get Student's High School Info** 
[(→)](#Summary)

In [14]:
# Irene

# find the common columns about high school related data between districts
common_cols = []
for df_name, df in df_l:
    dfd = df_d[df_name]
    student_info = dfd['student_info']
    high_school = dfd['high_school']
    high_school['grade9year'] = student_info['grade9year']
    
    years = sorted(student_info['grade9year'].unique())
    for y in years:
        common_cols.extend(high_school[high_school['grade9year'] == y].filter(regex=re.compile(r'FY'+str(y)+'.*')).columns)
common_cols = sorted(list(set([i[6:] for i in common_cols])))
common_cols

['days_absent_school1',
 'days_absent_school2',
 'days_absent_school3',
 'days_absent_school4',
 'gpa_school1',
 'gpa_school2',
 'gpa_school3',
 'grade_level',
 'high_school_code1',
 'high_school_code2',
 'high_school_code3',
 'high_school_code4',
 'unweightedclassrank_school1',
 'unweightedclassrank_school2',
 'unweightedclassrank_school3',
 'year_end_exit_code']

In [15]:
# Irene

# the columns that will be add to student_info
highschool_cols = ['high_school_code1', 'high_school_code2','high_school_code3', 'high_school_code4']

In [16]:
# Irene

# find the high school code when the student was on 9th grade level
# if there's no code data at all, return nan
# if the student has high school code data but it's not the 9th grade year one, return the first record of code
def get_high_school_code(x):
    return_value = None
    codes = x[1:][x[1:].notna()]
    if len(codes) == 0:
        return np.nan
    else:
        y = x['grade9year']
        ycodes = codes.filter(regex=re.compile(str(y)))
        ycodes = ycodes[ycodes.notna()]
        if len(ycodes) >= 1:
            return ycodes.values[0]
        else:
            return codes.values[0]

In [17]:
# Irene

# find high_school_code and store it to student_info
for df_name, df in df_l:
    dfd = df_d[df_name]
    student_info = dfd['student_info']
    high_school_code = dfd['high_school'].filter(regex=re.compile(r'.*high_school_code.*'))
    high_school_code = pd.concat([dfd['student_info']['grade9year'], high_school_code], axis=1)
    student_info['high_school_code'] = high_school_code.apply(get_high_school_code, axis=1)
    display(student_info.head())

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code
study_id,,,,,,,,,,,,,,
111152.00,2017,1,2002-10-25,F,Hispanic/Latino,0,0,1,0,1,0,0,0,nan
111154.00,2015,1,2001-03-20,F,Hispanic/Latino,0,0,0,0,0,0,0,0,nan
111158.00,2017,1,2003-03-27,F,Black/African American,0,0,1,0,1,0,0,0,nan
111172.00,2016,1,2001-12-11,F,Hispanic/Latino,0,1,0,0,0,0,0,0,nan
111178.00,2018,1,2004-05-12,F,Hispanic/Latino,1,0,1,0,1,0,0,0,nan

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code
study_id,,,,,,,,,,,,,,
1113631,2011,2,01/23/1996,F,Hispanic/Latino,0,0,0,1,0,1,0,0,nan
1119371,2011,2,03/29/1996,F,White,0,0,1,0,0,0,0,0,nan
1119961,2012,2,04/21/1996,M,Hispanic/Latino,0,0,0,0,0,0,0,0,nan
1161336,2012,2,11/30/1996,M,Hispanic/Latino,0,0,0,1,0,1,1,0,nan
1161776,2011,2,12/24/1995,F,Hispanic/Latino,0,0,0,0,0,0,0,0,nan

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code
study_id,,,,,,,,,,,,,,
102966224,2016,3,2001-03-23,F,Two or More,0,0,nan,0,1,0,0,0,122223.00
102966226,2016,3,2001-02-02,M,Hispanic/Latino,0,0,nan,0,1,0,0,0,122223.00
102966229,2016,3,2001-04-02,M,White,0,0,nan,0,1,0,0,0,122223.00
102966242,2016,3,2001-10-30,M,Black/African American,0,0,nan,0,1,0,0,0,122223.00
102966244,2016,3,2001-04-04,F,White,0,0,nan,0,1,0,0,0,122223.00

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code
study_id,,,,,,,,,,,,,,
2222173334,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan
2222173335,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan
2222173339,2006,4,None,None,None,0,0,nan,1,0,1,1,0,nan
2222173344,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan
2222173349,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code
study_id,,,,,,,,,,,,,,
4420444,2008,5,None,None,None,0,0,0,1,0,1,1,0,nan
4422444,2008,5,None,None,None,0,0,0,1,0,1,0,0,nan
41523444,2009,5,None,None,None,0,0,0,1,0,1,1,0,nan
41822444,2009,5,None,None,None,0,0,0,1,0,1,0,0,nan
41825444,2009,5,None,None,None,0,0,0,1,0,1,1,0,nan

#### **4. Get Student's College Info** 
[(→)](#Summary)

In [18]:
# Irene

# list the college graduation related columns
for df_name, df in df_l:
    college_grad = df_d[df_name]['college'].filter(regex=re.compile(r'^college.*'))
    print(college_grad.columns)

Index(['college_graduated', 'college_grad_date1', 'college_grad_degree1type',
       'college_grad_degree1detail', 'college_grad_name1',
       'college_grad_date2', 'college_grad_degree2type',
       'college_grad_degree2detail', 'college_grad_name2'],
      dtype='object')
Index(['college_graduated', 'college_grad_date1', 'college_grad_name1',
       'college_grad_date2', 'college_grad_name2', 'college_grad_date3',
       'college_grad_name3'],
      dtype='object')
Index(['college_graduated', 'college_grad_date1', 'college_grad_degree1type',
       'college_grad_degree1detail', 'college_grad_name1',
       'college_grad_date2', 'college_grad_degree2type',
       'college_grad_degree2detail', 'college_grad_name2',
       'college_grad_date3', 'college_grad_degree3type',
       'college_grad_degree3detail', 'college_grad_name3',
       'college_grad_date4', 'college_grad_degree4type',
       'college_grad_degree4detail', 'college_grad_name4'],
      dtype='object')
Index(['college_graduated', 'college_grad_date1', 'college_grad_degree1type',
       'college_grad_degree1detail', 'college_grad_name1',
       'college_grad_date2', 'college_grad_degree2type',
       'college_grad_degree2detail', 'college_grad_name2',
       'college_grad_date3', 'college_grad_degree3type',
       'college_grad_degree3detail', 'college_grad_name3',
       'college_grad_date4', 'college_grad_degree4type',
       'college_grad_degree4detail', 'college_grad_name4',
       'college_grad_date5', 'college_grad_degree5type',
       'college_grad_degree5detail', 'college_grad_name5'],
      dtype='object')
Index(['college_graduated', 'college_grad_date1', 'college_grad_degree1type',
       'college_grad_degree_detail1', 'college_grad_name1',
       'college_grad_date2', 'college_grad_degree2type',
       'college_grad_degree_detail2', 'college_grad_name2',
       'college_grad_date3', 'college_grad_degree3type',
       'college_grad_degree_detail3', 'college_grad_name3'],
      dtype='object')

In [19]:
# Irene

# a function that can find the highest degree that the students get
# degree_type = ['0 UNKNOWN', '1 CERTIFICATE', '2 ASSOCIATES', '3 BACHELORS',  '4 PROFESSIONAL', '5 MASTERS', '6 DOCTORATE']
def find_degree(x):
    x = sorted(x[x.notna()])
    if len(x) == 0:
        return np.nan
    else:
        return x[-1]

In [20]:
# Irene

# a function that can find the first degree that the students get
def first_degree(x):
    min_idx = None
    min_date = '2099-1-1' 	
    for idx, date in x.items():
        if idx[-1] == 'e':
            continue
        if date != None and date < min_date:
            min_date = date
            min_idx = idx
    if min_idx == None:
        return None
    else:   
        return 'college_grad_degree' + min_idx[-1] + 'type'

In [21]:
# Irene

# add college graduation data to student_info

# grad_cols = list(df_d['df4']['college'].filter(regex=re.compile(r'^college((?!date|detail|graduated).)*$')))

for df_name, df in df_l:
    dfd = df_d[df_name]
    college_grad = dfd['college'].filter(regex=re.compile(r'^college((?!detail|graduated).)*$')).copy()
    grad_concat = pd.DataFrame(columns=['num_degree', 'highest_degree', 'first_degree'], index=college_grad.index)
    
    # find the number of degrees the students get
    grad_concat['num_degree'] = college_grad.filter(regex=re.compile(r'name')).notna().sum(axis=1)
    
    if df_name != 'df2':
        for i in range(0, len(college_grad.columns), 3):           
            miss_degree_idx = college_grad[(college_grad.iloc[:, i+2].notna()) & (college_grad.iloc[:, i+1].isna())].index
            college_grad.loc[miss_degree_idx, college_grad.columns[i+1]] = '0 UNKNOWN'
            
        grad_concat['highest_degree'] = college_grad.filter(regex=re.compile(r'degree')).apply(find_degree, axis=1)
        
        degree_date_type = college_grad.filter(regex=re.compile(r'date|type'))
        locator = degree_date_type.apply(first_degree, axis=1)
        first_degree_l = []
        for i in degree_date_type.index:
            if locator.loc[i] == None:
                first_degree_l.append(None)
            else:
                first_degree_l.append(degree_date_type.loc[i, locator.loc[i]])        
        grad_concat['first_degree'] = first_degree_l
    else:
        name_df = college_grad.filter(regex=re.compile(r'name')).copy()
        miss_degree_idx = name_df[name_df.notna().sum(axis=1) > 0].index
        grad_concat.loc[miss_degree_idx, 'first_degree'] = '0 UNKNOWN'
        grad_concat.loc[miss_degree_idx, 'highest_degree'] = '0 UNKNOWN'
        
    dfd['student_info'] = pd.concat([dfd['student_info'], grad_concat], axis=1)
    display(dfd['student_info'].head())

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree
study_id,,,,,,,,,,,,,,,,,
111152.00,2017,1,2002-10-25,F,Hispanic/Latino,0,0,1,0,1,0,0,0,nan,0,NaN,None
111154.00,2015,1,2001-03-20,F,Hispanic/Latino,0,0,0,0,0,0,0,0,nan,0,NaN,None
111158.00,2017,1,2003-03-27,F,Black/African American,0,0,1,0,1,0,0,0,nan,0,NaN,None
111172.00,2016,1,2001-12-11,F,Hispanic/Latino,0,1,0,0,0,0,0,0,nan,0,NaN,None
111178.00,2018,1,2004-05-12,F,Hispanic/Latino,1,0,1,0,1,0,0,0,nan,0,NaN,None

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree
study_id,,,,,,,,,,,,,,,,,
1113631,2011,2,01/23/1996,F,Hispanic/Latino,0,0,0,1,0,1,0,0,nan,0,NaN,NaN
1119371,2011,2,03/29/1996,F,White,0,0,1,0,0,0,0,0,nan,0,NaN,NaN
1119961,2012,2,04/21/1996,M,Hispanic/Latino,0,0,0,0,0,0,0,0,nan,0,NaN,NaN
1161336,2012,2,11/30/1996,M,Hispanic/Latino,0,0,0,1,0,1,1,0,nan,1,0 UNKNOWN,0 UNKNOWN
1161776,2011,2,12/24/1995,F,Hispanic/Latino,0,0,0,0,0,0,0,0,nan,0,NaN,NaN

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree
study_id,,,,,,,,,,,,,,,,,
102966224,2016,3,2001-03-23,F,Two or More,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None
102966226,2016,3,2001-02-02,M,Hispanic/Latino,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None
102966229,2016,3,2001-04-02,M,White,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None
102966242,2016,3,2001-10-30,M,Black/African American,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None
102966244,2016,3,2001-04-04,F,White,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree
study_id,,,,,,,,,,,,,,,,,
2222173334,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None
2222173335,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None
2222173339,2006,4,None,None,None,0,0,nan,1,0,1,1,0,nan,2,2 ASSOCIATES,1 CERTIFICATE
2222173344,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None
2222173349,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree
study_id,,,,,,,,,,,,,,,,,
4420444,2008,5,None,None,None,0,0,0,1,0,1,1,0,nan,1,0 UNKNOWN,0 UNKNOWN
4422444,2008,5,None,None,None,0,0,0,1,0,1,0,0,nan,0,NaN,None
41523444,2009,5,None,None,None,0,0,0,1,0,1,1,0,nan,1,0 UNKNOWN,0 UNKNOWN
41822444,2009,5,None,None,None,0,0,0,1,0,1,0,0,nan,0,NaN,None
41825444,2009,5,None,None,None,0,0,0,1,0,1,1,0,nan,1,3 BACHELORS,3 BACHELORS

In [22]:
# Irene

# college enrollment related columns
common_cols2 = []
for df_name, df in df_l:
    college_info = df_d[df_name]['college'].filter(regex=re.compile(r'^(?!college_grad)'))
    common_cols2.extend(college_info.columns)
common_cols2 = sorted(list(set([i[6:] for i in common_cols2])))
set([i.split('_', 1)[-1] for i in common_cols2])

{'begin_date',
 'end_date',
 'enrollment_status',
 'name',
 'public_private',
 'type2or4year'}

In [23]:
# Irene

# Less Than 2 Years
def college_type(x, string):
    counter = Counter(x)
    count = 0
    if string == '4year_public':
        return counter[('4-year', 'Public')]
    elif string == '2year_public':
        return counter[('2-year', 'Public')]
    elif string == 'less2year_public':
        return counter[('Less Than 2 Years', 'Public')]
    elif string == '4year_private':
        return counter[('4-year', 'Private')]
    elif string == '2year_private':
        return counter[('2-year', 'Private')]
    elif string == 'less2year_private':
        return counter[('Less Than 2 Years', 'Private')]
    elif string == '4year':
        return college_year(counter, '4')
    elif string == '2year':
        return college_year(counter, '2')
    elif string == 'less2year':
        return college_year(counter, 'L')

In [24]:
# Irene

def college_year(counter, key):
    count = 0
    for k, v in counter.items():
        if k == None:
            continue
        elif k[0][0] == key:
            count += v
    return count

In [25]:
# Irene

# add enrolled college info to student_info
for df_name, df in df_l:
    dfd = df_d[df_name]
    student_info = dfd['student_info']
    college_info = dfd['college'].filter(regex=re.compile(r'^(?!college_grad)'))
                
    extract_d1 = {id:[] for id in college_info.index}
    extract_d2 = {id:[] for id in college_info.index}
    for i in range(0, len(college_info.columns), 6):
        
        # for finding the last enrollment status
        segment1 = college_info.iloc[:, i+1:i+4]
        segment1_notna = segment1[segment1.iloc[:,2].notna()]
        segment1_dict = segment1_notna.T.to_dict('list')
        
        for id in segment1_dict.keys():
            values = tuple(segment1_dict[id])
            if values not in extract_d1[id]:
                extract_d1[id].append(values)
        
        # for finding all the enrolled college
        segment2 = college_info.iloc[:, i+4:i+6]
        segment2_notna = segment2[segment2.notna().sum(axis=1) > 0]
        segment2_dict = segment2_notna.T.to_dict('list')
        
        for id in segment2_dict.keys():
            values = tuple(segment2_dict[id])
            if values not in extract_d2[id]:
                extract_d2[id].append(values)
                
    # for finding the last enrollment status
    college_studying = []
    for id in extract_d1.keys():
        try:
            if df_name == 'df2':
                month = 4
            else:
                month = 11
            if (pd.DatetimeIndex([extract_d1[id][-1][0]]).year[0] == dfd['latest_year']) \
                    & (pd.DatetimeIndex([extract_d1[id][-1][0]]).month[0] >= month) \
                    & (extract_d1[id][-1][1][0] != '6'):
                college_studying.append(1)
            else:
                college_studying.append(0)
        except:
            college_studying.append(0)
    student_info['college_studying'] = college_studying
    grad_idx = student_info[student_info['college_graduate']==1].index
    student_info.loc[grad_idx, 'college_studying'] = 0

    # for finding all the enrolled college
    college_df = pd.DataFrame.from_dict(extract_d2, orient='index')
    
    college_concat = pd.DataFrame(index=college_df.index, 
                                  columns=['4year', '2year', 'less2year', 
                                           '4year_public', '4year_private', 
                                           '2year_public', '2year_private', 
                                           'less2year_public', 'less2year_private']).fillna(0)
    for c in college_concat:
        college_concat[c] = college_df.apply(college_type, axis=1, string=c)

    dfd['student_info'] = pd.concat([dfd['student_info'], college_concat], axis=1)
    display(dfd['student_info'].head())

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree,4year,2year,less2year,4year_public,4year_private,2year_public,2year_private,less2year_public,less2year_private
111152.00,2017,1,2002-10-25,F,Hispanic/Latino,0,0,1,0,1,0,0,0,nan,0,NaN,None,0,0,0,0,0,0,0,0,0
111154.00,2015,1,2001-03-20,F,Hispanic/Latino,0,0,0,0,0,0,0,0,nan,0,NaN,None,0,0,0,0,0,0,0,0,0
111158.00,2017,1,2003-03-27,F,Black/African American,0,0,1,0,1,0,0,0,nan,0,NaN,None,0,0,0,0,0,0,0,0,0
111172.00,2016,1,2001-12-11,F,Hispanic/Latino,0,1,0,0,0,0,0,0,nan,0,NaN,None,0,0,0,0,0,0,0,0,0
111178.00,2018,1,2004-05-12,F,Hispanic/Latino,1,0,1,0,1,0,0,0,nan,0,NaN,None,0,0,0,0,0,0,0,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree,4year,2year,less2year,4year_public,4year_private,2year_public,2year_private,less2year_public,less2year_private
1113631,2011,2,01/23/1996,F,Hispanic/Latino,0,0,0,1,0,1,0,1,nan,0,NaN,NaN,1,0,0,0,1,0,0,0,0
1119371,2011,2,03/29/1996,F,White,0,0,1,0,0,0,0,0,nan,0,NaN,NaN,0,0,0,0,0,0,0,0,0
1119961,2012,2,04/21/1996,M,Hispanic/Latino,0,0,0,0,0,0,0,0,nan,0,NaN,NaN,0,0,0,0,0,0,0,0,0
1161336,2012,2,11/30/1996,M,Hispanic/Latino,0,0,0,1,0,1,1,0,nan,1,0 UNKNOWN,0 UNKNOWN,1,1,0,1,0,1,0,0,0
1161776,2011,2,12/24/1995,F,Hispanic/Latino,0,0,0,0,0,0,0,0,nan,0,NaN,NaN,0,0,0,0,0,0,0,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree,4year,2year,less2year,4year_public,4year_private,2year_public,2year_private,less2year_public,less2year_private
102966224,2016,3,2001-03-23,F,Two or More,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None,0,0,0,0,0,0,0,0,0
102966226,2016,3,2001-02-02,M,Hispanic/Latino,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None,0,0,0,0,0,0,0,0,0
102966229,2016,3,2001-04-02,M,White,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None,0,0,0,0,0,0,0,0,0
102966242,2016,3,2001-10-30,M,Black/African American,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None,0,0,0,0,0,0,0,0,0
102966244,2016,3,2001-04-04,F,White,0,0,nan,0,1,0,0,0,122223.00,0,NaN,None,0,0,0,0,0,0,0,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree,4year,2year,less2year,4year_public,4year_private,2year_public,2year_private,less2year_public,less2year_private
2222173334,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None,0,1,0,0,0,1,0,0,0
2222173335,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None,0,1,0,0,0,1,0,0,0
2222173339,2006,4,None,None,None,0,0,nan,1,0,1,1,0,nan,2,2 ASSOCIATES,1 CERTIFICATE,1,1,0,1,0,1,0,0,0
2222173344,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None,0,1,0,0,0,1,0,0,0
2222173349,2006,4,None,None,None,0,0,nan,1,0,1,0,0,nan,0,NaN,None,0,1,0,0,0,1,0,0,0

,grade9year,district,birth_date,gender,ethnicity,ell_indicator,sped_indicator,free_reduced_lunch_indicator,high_school_grad,high_school_studying,college_enroll,college_graduate,college_studying,high_school_code,num_degree,highest_degree,first_degree,4year,2year,less2year,4year_public,4year_private,2year_public,2year_private,less2year_public,less2year_private
4420444,2008,5,None,None,None,0,0,0,1,0,1,1,0,nan,1,0 UNKNOWN,0 UNKNOWN,1,0,0,0,1,0,0,0,0
4422444,2008,5,None,None,None,0,0,0,1,0,1,0,0,nan,0,NaN,None,1,0,0,1,0,0,0,0,0
41523444,2009,5,None,None,None,0,0,0,1,0,1,1,0,nan,1,0 UNKNOWN,0 UNKNOWN,2,0,0,1,1,0,0,0,0
41822444,2009,5,None,None,None,0,0,0,1,0,1,0,0,nan,0,NaN,None,0,1,0,0,0,1,0,0,0
41825444,2009,5,None,None,None,0,0,0,1,0,1,1,0,nan,1,3 BACHELORS,3 BACHELORS,1,1,0,1,0,1,0,0,0

#### **5. Drop Students and Save to Files** 
[(→)](#Summary)

In [27]:
# Irene

# drop the students who has no college related info at all.
# e.g. like a student was a 9th grader at 2006 would not have college info in the given dataset
for df_name, df in df_l:
    dfd = df_d[df_name]
    student_info = dfd['student_info']
    no_college_info = student_info[student_info['grade9year'] < dfd['earliest_year'] - 3].index
    dfd['student_info'].drop(index=no_college_info, inplace=True)
    
    display(dfd['student_info'].shape)

(61727, 26)

(33023, 26)

(36937, 26)

(25546, 26)

(66924, 26)

In [29]:
# Irene

df_all = pd.concat([df_d['df1']['student_info'].dropna(subset=['grade9year']), 
                    df_d['df2']['student_info'].dropna(subset=['grade9year']), 
                    df_d['df3']['student_info'].dropna(subset=['grade9year']),
                    df_d['df4']['student_info'].dropna(subset=['grade9year']), 
                    df_d['df5']['student_info'].dropna(subset=['grade9year'])])
df_all
df_all.to_csv('d_9th.csv')